import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Group Chat Socket IO | NextJs</title>
        <meta
          name="description"
          content="Generated by dmak.freelancer@gmail.com"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="bgimg">
          <div className="topleft">
            <p>Group Chat</p>
          </div>
          <div className="middle">
            <h1>
              Welcome to our chatting App
              <span style={{ color: "red" }}> ❤</span>
            </h1>
            <Link href="/join">
              <a
                style={{
                  marginTtop: "50px",
                  width: "100%",
                  backgroundColor: "#ffffff",
                  color: "#080710",
                  padding: "15px 0",
                  fontSize: "18px",
                  fontWeight: "600",
                  borderRadius: " 5px",
                  cursor: "pointer",
                  padding: "20px",
                }}
              >
                Join the Chat
              </a>
            </Link>
          </div>
          <div className="bottomleft">
            <a href="mailto:dmak.freelancer@gmail.com">
              dmak.freelancer@gmail.com
            </a>
          </div>
        </div>
      </main>
    </div>
  );
}
